baseURL = "jeoqm-77.top"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh"
title = "野火"
copyright = "立谈中，死生同，一诺千金重"
theme = "diary"

[markup]
[markup.highlight]
   codeFences = true
   guessSyntax = false
   hl_Lines = ""
   lineNoStart = 1
   lineNos = false
   lineNumbersInTable = true
   noClasses = true
   style = "monokai"
   tabWidth = 4

[params]
subtitle = "远芳侵古道，晴翠接荒城"
enableGitalk = false # 开启Gitalk
enableGiscus = true

# Twitter Card and Open Graph settings

enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
owner = "Qvisl9"
repo = "Gitalk"  #如Gitalk
client_id = "Ov23liHCM6AhZ3WqgzNp" # 填入记录的Client ID
client_secret = "e4b26f734f08d3a769ea134106aa973052a3dd33" # 填入记录的Client Secret

[[menu.main]]
url = "/Articels"
name = "文章"
weight = 1

[[menu.main]]
url = "/tags"
name = "标签"
weight = 2

[[menu.main]]
url = "https://image.jeoqm-77.top/"
name = "图床"
weight = 3

[[menu.main]]
url = "https://zt.jeoqm-77.top/"
name = "探针"
weight = 4